export const NAV_LINK = {
  OPS: "/ops",
  LMS: "/lms",
  STUDENT: "/student",
  MY_PROFILE: "/my-profile",
  MY_PROFILE_OVERVIEW: "/my-profile/overview",
  MY_PROFILE_SETTINGS: "/my-profile/settings",
  LOGIN: "/login",

  WEEKLY_NORM_REGISTRATION: "/lms/weekly-norm-registration",
  MY_CALENDAR: "/lms/my-calendar",
  TIME_OFF_REGISTRATION: "/lms/time-off-registration",

  MANAGE_USERS: "/ops/user",
  TEACHER_LIST: "/ops/user/teacher/list",
  RECEPTIONIST_LIST: "/ops/user/receptionist/list",
  MANAGE_ROOMS: "/ops/room/list",
  MANAGE_REQUESTS: "/ops/request",
  WEEKLY_NORM_LIST: "/ops/request/weekly-norm/list",
  TIME_OFF_LIST: "/ops/request/time-off/list",
  BUSY_SCHEDULE_LIST: "/ops/request/busy-schedule/list",
  TEACHING_MODE_LIST: "/ops/request/teaching-mode/list",
  MANAGE_CALENDAR: "/ops/calendar",
  MANAGE_COURSES: "/ops/course/list",

  MY_CLASS: "/my-class",
};

export const NAV_TITLE = {
  OPS: "OPS",
  LMS: "LMS",
  HOME: "Trang chủ",
  MANAGE_USERS: "Quản lý người dùng",
  TEACHER_LIST: "Quản lý giáo viên",
  RECEPTIONIST_LIST: "Quản lý lễ tân",
  MANAGE_ROOMS: "Quản lý phòng học",
  MY_PROFILE: "Thông tin cá nhân",
  WEEKLY_NORM_REGISTRATION: "Đăng ký định mức tuần",
  MY_CALENDAR: "Lịch của tôi",
  TIME_OFF_REGISTRATION: "Đăng ký lịch nghỉ cố định",
  MANAGE_REQUESTS: "Quản lý yêu cầu",
  WEEKLY_NORM_LIST: "Đăng ký định mức tuần",
  TIME_OFF_LIST: "Đăng ký lịch nghỉ cố định",
  BUSY_SCHEDULE_LIST: "Đăng ký lịch bận",
  TEACHING_MODE_LIST: "Đổi hình thức dạy",
  MANAGE_CALENDAR: "Quản lý lịch",
  MANAGE_COURSES: "Quản lý khoá học",
  MY_CLASS: "Lớp của tôi",
};
