export const NAV_LINK = {
  OPS: "/ops",
  TEACHER: "/teacher",
  STUDENT: "/student",
  MY_PROFILE: "/my-profile",
  MY_PROFILE_OVERVIEW: "/my-profile/overview",
  MY_PROFILE_SETTINGS: "/my-profile/settings",
  LOGIN: "/login",

  WEEKLY_NORM_REGISTRATION: "/teacher/weekly-norm-registration",
  MY_CALENDAR: "/teacher/my-calendar",
  TIME_OFF_REGISTRATION: "/teacher/time-off-registration",
  BUSY_SCHEDULE_REGISTRATION: "/teacher/busy-schedule-registration",

  MANAGE_USERS: "/ops/user",
  TEACHER_LIST: "/ops/user/teacher/list",
  STUDENT_LIST: "/ops/user/student/list",
  STAFF_LIST: "/ops/user/staff/list",
  MANAGER_LIST: "/ops/user/manager/list",
  MANAGE_ROOMS: "/ops/room/list",
  MANAGE_FIELDS: "/ops/field/list",
  MANAGE_DEPARTMENTS: "/ops/department/list",
  MANAGE_REQUESTS: "/ops/request",
  WEEKLY_NORM_LIST: "/ops/request/weekly-norm/list",
  TIME_OFF_LIST: "/ops/request/time-off/list",
  BUSY_SCHEDULE_LIST: "/ops/request/busy-schedule/list",
  MANAGE_CALENDAR: "/ops/calendar",
  MANAGE_COURSES: "/ops/course/list",
  MANAGE_CLASSES: "/ops/class/list",

  MY_CLASS: "/my-class",

  CLASS_DETAIL_OVERVIEW: (id: string) => `/ops/class/${id}/overview`,
  CLASS_DETAIL_SETTINGS: (id: string) => `/ops/class/${id}/settings`,
  CLASS_DETAIL_CALENDAR: (id: string) => `/ops/class/${id}/calendar`,
  CLASS_DETAIL_STUDENTS: (id: string) => `/ops/class/${id}/students`,

  MY_NOTIFICATION: "/my-notification",

  USER_DETAIL_OVERVIEW: (id: string) => `/ops/user/${id}/overview`,
  USER_DETAIL_SETTINGS: (id: string) => `/ops/user/${id}/settings`,
};

export const NAV_TITLE = {
  HOME: "Trang chủ",
  MANAGE_USERS: "Quản lý người dùng",
  TEACHER_LIST: "Quản lý giáo viên",
  STUDENT_LIST: "Quản lý học viên",
  STAFF_LIST: "Quản lý nhân viên",
  MANAGER_LIST: "Quản lý người quản lý",
  MANAGE_ROOMS: "Quản lý phòng học",
  MANAGE_FIELDS: "Quản lý loại chứng chỉ",
  MANAGE_DEPARTMENTS: "Quản lý phòng ban",
  MY_PROFILE: "Thông tin cá nhân",
  WEEKLY_NORM_REGISTRATION: "Đăng ký định mức tuần",
  MY_CALENDAR: "Thời khóa biểu",
  TIME_OFF_REGISTRATION: "Đăng ký lịch nghỉ cố định",
  BUSY_SCHEDULE_REGISTRATION: "Đăng ký lịch bận",
  MANAGE_REQUESTS: "Quản lý yêu cầu",
  WEEKLY_NORM_LIST: "Đăng ký định mức tuần",
  TIME_OFF_LIST: "Đăng ký lịch nghỉ cố định",
  BUSY_SCHEDULE_LIST: "Đăng ký lịch bận",
  MANAGE_CALENDAR: "Quản lý thời khóa biểu",
  MANAGE_COURSES: "Quản lý khoá học",
  MY_CLASS: "Các lớp được giao",
  MANAGE_CLASSES: "Quản lý lớp học",
  CLASS_DETAIL: "Chi tiết lớp học",
  USER_DETAIL: "Chi tiết người dùng",
};
