stages:
  - build
  - deploy

# New staging build job
build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - yarn install --frozen-lockfile # ensure dependencies are installed
    - npx nx build web
  tags:
    - co-gitlab-runner
  only:
    - tags

# New staging deploy job
deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - sudo kill -9 $(sudo ss -tulnp | grep ':$WEB_PORT' | grep -oP 'pid=\K\d+') || true
    - sudo kill -9 $(sudo ss -tulnp | grep ':$NOTI_PORT' | grep -oP 'pid=\K\d+') || true
    - sudo kill -9 $(sudo ss -tulnp | grep ':$CO_PORT' | grep -oP 'pid=\K\d+') || true
    - nohup npx nx start web > web.log 2>&1 &
    - nohup npx nx serve noti > noti.log 2>&1 &
    - nohup npx nx serve co > co.log 2>&1 &
  tags:
    - co-gitlab-runner
  only:
    - tags
