version: '3.8'

services:
  postgres:
    container_name: postgres_co
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_co:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_co:
